apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootappdeployment
  namespace: test-ns
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      name: springbootpod
      labels:
        app: springbootapp
    spec:
      containers:
      - name: springbootcontainer
        image: hiralalsahu/spring-boot-mongo:latest
      imagePullSecrets: 
      - name: regcred
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256M
          limits:
            cpu: 200m
            memory: 500M
        env:
          - name: MONGO_DB_USERNAME
            value: devdb
          - name: MONGO_DB_PASSWORD
            value: devdb123
          - name: MONGO_DB_HOSTNAME
            value: mongodbsvc
---
apiVersion: v1
kind: Service
metadata:
  name: springbootsvc
  namespace: test-ns
spec:
  selector:
    app: springbootapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mongodbapp
  template:
    metadata:
      name: mongodbpod
      labels:
        app: mongodbapp
    spec:
      containers:
      - name: mongodbcontainer
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 256M
          limits:
            cpu: 200m
            memory: 500M
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb123
        volumeMounts:
        - name: localvolumes
          mountPath: /data/db
      volumes:
      - name: localvolumes
        hostPath:
          path: /mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
  namespace: test-ns
spec:
  selector:
    app: mongodbapp
  ports:
  - port: 27017
    targetPort: 27017
